const ESCUDOS = {
  'Internacional': 'escudos/internacional.png',
  'Corinthians': 'escudos/corinthians.png',
  'Athletico-PR': 'escudos/athletico.png',
  'Vitória': 'escudos/vitoria.png',
  'Fluminense': 'escudos/fluminense.png',
  'Bahia': 'escudos/bahia.png',
  'Mirassol': 'escudos/mirassol.png',
  'Remo': 'escudos/remo.png',
  'Flamengo': 'escudos/flamengo.png',
  'Palmeiras': 'escudos/palmeiras.png',
  'Coritiba': 'escudos/coritiba.png',
  'Cruzeiro': 'escudos/cruzeiro.png',
  'Vasco': 'escudos/vasco.png',
  'Santos': 'escudos/santos.png',
  'Fortaleza': 'escudos/fortaleza.png',
  'Atlético-MG': 'escudos/atletico.png',
  'Juventude': 'escudos/juventude.png',
  'Chapecoense': 'escudos/chapeco.png',
  'Botafogo': 'escudos/botafogo.png',
  'RB Bragantino': 'escudos/bragantino.png',
  'São Paulo': 'escudos/saopaulo.png',
  'Grêmio': 'escudos/gremio.png',
  'Vitória': 'escudos/vitoria.png', 
    };