const ESCUDOS = {
  'Internacional': 'escudos/internacional.png',
  'Corinthians': 'escudos/corinthians.png',
  'Athletico-PR': 'escudos/athletico.png',
  'Vitória': 'escudos/vitoria.png',
  'Fluminense': 'escudos/fluminense.png',
  'Bahia': 'escudos/bahia.png',
  'Mirassol': 'escudos/mirassol.png',
  'Remo': 'escudos/remo.png',
  'Flamengo': 'escudos/flamengo.png',
  'Palmeiras': 'escudos/palmeiras.png',
  'Coritiba': 'escudos/coritiba.png',
  'Cruzeiro': 'escudos/cruzeiro.png',
  'Vasco': 'escudos/vasco.png',
  'Santos': 'escudos/santos.png',
  'Fortaleza': 'escudos/fortaleza.png',
  'Atlético-MG': 'escudos/atletico.png',
  'Juventude': 'escudos/juventude.png',
  'Chapecoense': 'escudos/chapeco.png',
  'Botafogo': 'escudos/botafogo.png',
  'RB Bragantino': 'escudos/bragantino.png',
  'São Paulo': 'escudos/saopaulo.png',
  'Grêmio': 'escudos/gremio.png',
  'Vitória': 'escudos/vitoria.png', 
  'Ind. Rivadavia': 'escudos/independiente.png',
  'Estudiantes': 'escudos/estudiantes.png',
  'Uni. Católica': 'escudos/universidad.png',
  'Tolima': 'escudos/tolima.png',
  'Ind. del Valle': 'escudos/delvalle.png',
  'Cerro Porteno': 'escudos/cerro.png',
  'Platense': 'escudos/platense.png',
  'Coquimbo Unido': 'escudos/coquimbo.png',
  'LDU': 'escudos/ldu.png',
  'Rosario Central': 'escudos/rosario.png',
    };